/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [BranchCode]
      , [RefNO]    
	   , [DecNO]
	   , [DocStatus] 
      , [InvNOList]    
      , [CmpCode]
	   , [NameThai]   
      , [NameEng]
	   , [VesselName]
      , [VoyNumber]
      , [ArrivalDate]
      , [MasterBL]
      , [HouseBL]
	   , [ReleasePort]
      , [DischargePort]
      , [OriginCountry]
      , [ConsCountry]
	   , [UDateDeclare]
      , [UDateRelease]
      , [UDateActual]
	   , [ItemNO]
      , [DecItemNO]
      , [TariffCode]
      , [TariffSeq]
      , [StatCode]
      , [ImportTariff]
      , [PrivilegeCode]
	   , [PdtDescriptionT]
      , [PdtDescriptionE]
	  , [BrandName]   
      , [DOriginCountry]
      , [NetWeight]
      , [GrossWeight]
      , [DWeightUnit]
      , [TariffQty]
      , [TariffUnit]
      , [SalesCur]     
      , [SalesRate]
      , [SalesPrice]
      , [SalesPriceTHB]
      , [SalesPackUnit]
      , [SalesPackQty]
      , [SalesTotalPrice]
      , [DSalesNetPriceTHB]
	  , [DSalesCIFPrice]
      , [DSalesCIFPriceTHB]



FROM [ECS_DATA2].[dbo].[qDecI_DeclareD]
WHERE (year([ArrivalDate]) BETWEEN '2016' AND '2018') AND [CmpCode] = '0105552012096'and left(RefNO,1)= 'D' and left(DecNO,1)='A' AND NOT DocStatus='99';


/*WHERE (year([ArrivalDate]) BETWEEN '2016' AND '2019') AND [CmpCode] = '0105552012096'; */